### ISSUE TITLE
Fails gathering facts

### ISSUE THREAD

**Issue by lashomb** [ANTS-Framework/ants#1]
Tried to run `sudo ./ants.py` as the README suggests.

Starting Ansible Pull at 2017-09-07 13:30:51
/usr/local/bin/ansible-pull --clean -f -i /Users/testuser/Downloads/ants-1.1 2/client/inventory_default.py -d /var/root/.ants_playbook -U https://github.com/ANTS-Framework/playbook.git -C master main.yml --accept-host-key

#### An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    IndexError: list index out of range
```
Sep 07 2017 13:02:05 CDT	TASK [Gathering Facts] ***************************************************************************************
Sep 07 2017 13:02:05 CDT	fatal: [TESTMAC]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_7iqq4W/ansible_module_setup.py\", line 139, in <module>\n    main()\n  File \"/tmp/ansible_7iqq4W/ansible_module_setup.py\", line 131, in main\n    data = get_all_facts(module)\n  File \"/tmp/ansible_7iqq4W/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3935, in get_all_facts\n  File \"/tmp/ansible_7iqq4W/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3878, in ansible_facts\n  File \"/tmp/ansible_7iqq4W/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2715, in populate\n  File \"/tmp/ansible_7iqq4W/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2806, in get_interfaces_info\n  File \"/tmp/ansible_7iqq4W/ansible_modlib.zip/ansible/module_utils/facts.py\", line 2869, in parse_inet_line\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by aschwanb** [comment]
The path for your inventory script looks strange: ` /Users/testuser/Downloads/ants-1.1 2/client/inventory_default.py`

I assume you are running ants on macOS. If so, how did you install it? If you use the pkg installer, the inventory script should be installed to `/usr/local/ants/inventory_default.py`

Also, `/usr/local/ants` well be added to your PATH, so you can ants with `sudo ants.py`
(no `./` required)

Could you exekute the pkg installer and try again?

**Comment by lashomb** [comment]
I misread the README.... I thought I could just run it without install... doh. Can close this, apologies.

> 2. Install the latest ANTS client, open the terminal and start an ANTS run by typing ants.py.

**Comment by JanWelker** [comment]
Thanks for the info. We try to keep a complete documentation here: 
[ANTS Documenation](https://ants-framework.github.io/)
