### ISSUE TITLE
Logstash logger plugin fields change type

### ISSUE THREAD

**Issue by JanWelker** [ANTS-Framework/ants#31]
The fields written to logstash should have stable types. Instead they change type from time to time.

Example:
ansible_results_executable flip-flops between string and Boolean
the same is true for:
ansible_item
ansible_results_result.item

**Comment by aschwanb** [comment]
This will be addresses in the following branch: https://github.com/ANTS-Framework/ants/tree/update_elk_logging

**Comment by aschwanb** [comment]
Merged #32 which addresses this issue.
